### ISSUE TITLE
12. Clear message icon when read

### ISSUE THREAD

**Issue by JoeShep** [NSS-Day-Cohort-49/giffygram-lolcatz#1]
As a gifophile, when I read my messages, the number in the NavBar notification should be reset to 0

**Given** that a person has clicked the message notification to view private messages
**When** the person clicks the logo to view the post list
**Then** message notification number should be set to 0

**Comment by auntviv** [comment]
- The NavBar notification should be SET to 0.
-Messages will be saved, true false boolean in persistent
