### ISSUE TITLE
1. Log in with existing credentials

### ISSUE THREAD

**Issue by JoeShep** [NSS-Day-Cohort-49/giffygram-lolcatz#12]
As a gifophile, I want to log in with my credentials

**Given** that a person wants to use Giffygram
**And** has entered in a valid email and password
**When** the person clicks on the login button
**Then** the person should see the list of posts

**Comment by auntviv** [comment]
- Separate page from the main feed (should reference the users from our permanent state)
- Make the enter a key event listener as opposed to a click event listener.
- Build a form for the user to type in username and password (input field)
- Luke will do a Parallax for the login and main pages.
- Add window alert that will inform user if email/password is invalid.

**Comment by hcrudge** [comment]
Create dummy user data in the permanent state to represent registered users.
Stretch goal - add a form to add users to the database/permanent state.
