### ISSUE TITLE
10. Read private messages

### ISSUE THREAD

**Issue by JoeShep** [NSS-Day-Cohort-49/giffygram-lolcatz#3]
As an authenticated user, I would like to be able to read all private messages sent to me by other users

**Given** that a person has provided proper authentication details
**When** the person is viewing the post feed
**And** there are 1+ unread messages sent from other users
**Then** there should be a notification in the navigation bar displaying the number of messages

**Given** that a person has provided proper authentication details
**And** there are 1+ unread messages sent from other users
**When** the person clicks the notification affordance
**Then** the post feed should be replaced with a list of messages

**Given** that a person has provided proper authentication details
**And** the person is viewing the message list
**When** the person clicks the application icon i the navigation bar
**Then** the list of messages should be replaced with a list of posts

**Comment by auntviv** [comment]
- In the nav bar we should be able to see the number of unread dm's
- Unread messages (logo) will take us to the dm's page 
- Fetch Get to pull the permanent state messages and display them
- Add separate logo upon page switches? One logo for main page, one for DM's (worded weirdly but we get it right? I hope so)
